services:
  - type: web
    name: study_chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn project_name.wsgi:application"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
