PREDEFINED_RESPONSES = {
    "What is a variable in Python?": "A variable is a name that refers to a value. You create variables using '='. Example: x = 5.",
    "Explain the difference between a list and a tuple.": "A list is mutable (can be changed), while a tuple is immutable (cannot be changed). Lists use [] and tuples use ().",
    "How do you write a function in Python?": "Use the 'def' keyword. Example: def greet(): print('Hello!'). Call it with greet().",
    "What is the purpose of the 'if __name__ == \"__main__\"' statement?": "It ensures that code runs only when the file is executed directly, not when imported as a module.",
    "What are Python loops?": "Loops in Python are used to repeat a block of code. The two main types are 'for' loops and 'while' loops.",
    "Explain Python's range() function.": "range() generates a sequence of numbers. Example: for i in range(5) gives numbers 0 to 4.",
    "What is a dictionary in Python?": "A dictionary is a collection of key-value pairs. Example: my_dict = {'key': 'value'}.",
    "What is a Python module?": "A module is a file containing Python code that can be imported into another script. Example: import math.",
    "What is the difference between 'is' and '==' in Python?": "'is' checks for object identity, while '==' checks for value equality.",
    "How do you handle exceptions in Python?": "Use 'try', 'except', and optionally 'finally' blocks to handle exceptions.",
    "What is a lambda function?": "A lambda function is an anonymous function. Example: lambda x: x * 2.",
    "What are Python's data types?": "Common data types include int, float, str, list, tuple, dict, set, and bool.",
    "What is the purpose of the 'pass' statement?": "'pass' is a placeholder that does nothing but avoids syntax errors.",
    "How do you comment in Python?": "Use # for single-line comments and triple quotes for multi-line comments.",
    "What is Python's 'import' statement?": "It allows you to include code from other modules. Example: import math.",
    "What is a Python class?": "A class is a blueprint for creating objects. Example: class Dog: def __init__(self, name): self.name = name.",
    "What is Python's 'with' statement?": "The 'with' statement is used for resource management, such as opening files.",
    "How do you create a list comprehension?": "Use square brackets to generate a list. Example: [x**2 for x in range(5)].",
    "What is the difference between 'break' and 'continue'?": "'break' exits a loop, while 'continue' skips to the next iteration.",
    "What is a variable in JavaScript?": "A variable stores data. Use 'var', 'let', or 'const'. Example: let x = 5;",
    "What is the difference between let and const?": "'let' allows the variable to be reassigned. 'const' declares a variable that cannot be reassigned.",
    "How do you write a function in JavaScript?": "Use the 'function' keyword. Example: function greet() { console.log('Hello!'); } Call it with greet().",
    "What is the purpose of the 'this' keyword?": "'this' refers to the current object in a function or method.",
    "What are JavaScript loops?": "Loops are used to execute a block of code multiple times. Examples are 'for', 'while', and 'do-while' loops.",
    "What is an array in JavaScript?": "An array stores multiple values in a single variable. Example: let arr = [1, 2, 3];",
    "Explain the difference between == and === in JavaScript.": "== checks for value equality, while === checks for both value and type equality.",
    "What is a callback function?": "A callback function is a function passed as an argument to another function, which is then executed after the operation.",
    "What are JavaScript events?": "Events are actions or occurrences that happen in the browser, like clicks or key presses.",
    "What is the DOM in JavaScript?": "The Document Object Model represents the HTML structure of a webpage, which JavaScript can manipulate.",
    "What is the difference between null and undefined?": "'null' is an assigned value meaning 'no value', while 'undefined' means a variable has been declared but not assigned.",
    "How do you add an event listener in JavaScript?": "Use addEventListener(). Example: element.addEventListener('click', function() { alert('Clicked!'); });",
    "What is the purpose of promises in JavaScript?": "Promises handle asynchronous operations, allowing code to execute without blocking.",
    "What is async/await in JavaScript?": "async/await allows asynchronous code to be written in a synchronous manner.",
    "What are JavaScript objects?": "Objects are collections of key-value pairs. Example: let obj = { name: 'Alice', age: 25 };",
    "What is a prototype in JavaScript?": "A prototype is an object from which other objects inherit properties.",
    "What is hoisting in JavaScript?": "Hoisting is JavaScript's default behavior of moving declarations to the top of the scope.",
    "How do you comment in JavaScript?": "Use // for single-line comments and /* */ for multi-line comments.",
    "What is the difference between function expressions and declarations?": "Function declarations are hoisted, while expressions are not.",
    "What is a JavaScript closure?": "A closure is a function that remembers its scope even after the outer function has finished execution."
}
